CREATE DATABASE clinica_candido_torres_database;

USE clinica_candido_torres_database;

CREATE TABLE USUARIO(
	IDUSUARIO INT(5) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(50) NOT NULL,
	TIPOUSUARIO VARCHAR(50) NOT NULL
);

CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(100) NOT NULL,
	NUMEROPRONTUARIO VARCHAR(100) NULL,
	SEXO VARCHAR(50) NULL,
	DATANASC VARCHAR(50) NOT NULL,
	CPF VARCHAR(50) NOT NULL,
        RG VARCHAR(50)  NULL,
        EMAIL VARCHAR(50) NULL,
        PROFISSAO VARCHAR(50) NULL,
        TELEFONE VARCHAR(50),
        CELULAR VARCHAR(50) NULL,
        INDICACAO VARCHAR(50) NULL,
        ESTADOCIVIL VARCHAR(50) NULL,
        ENDERECO VARCHAR(50) NULL,
        BAIRRO VARCHAR(50) NULL,
        NUMERO VARCHAR(50) NULL,
        CIDADE VARCHAR(50) NULL,
        ESTADO VARCHAR(50) NULL,
        COMPLEMENTO VARCHAR(50) NULL,
        CEP VARCHAR(50) NULL
);


CREATE TABLE MEDICO(
	IDMEDICO INT(11) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	DTANASCIMENTO VARCHAR(255) NOT NULL,
	CONSELHO VARCHAR(255) NOT NULL,
	ESPECIALIDADE VARCHAR(255) NOT NULL,
	FUNCAO VARCHAR(255) NOT NULL,
	TIPODEATENDIMENTO VARCHAR(255) NOT NULL
);
