CREATE DATABASE clinica_candido_torres_database;

USE clinica_candido_torres_database;

CREATE TABLE USUARIO(
	IDUSUARIO INT(5) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(50) NOT NULL,
	TIPOUSUARIO VARCHAR(50) NOT NULL
);